export function createMockWorker(overrides?: {}): {
    id: any;
    organization_id: any;
    employee_id: any;
    status: string;
    hire_date: string;
    termination_date: null;
    primary_department_id: any;
    primary_location_id: any;
    default_hourly_rate: number;
    max_hours_per_week: number;
    employment_type: string;
    first_name: string;
    last_name: string;
    email: string;
    phone: string;
    department_name: string;
    location_name: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockRole(overrides?: {}): {
    id: any;
    organization_id: any;
    name: string;
    code: string;
    description: string;
    department_id: any;
    required_certifications: string[];
    default_hourly_rate: number;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockStation(overrides?: {}): {
    id: any;
    organization_id: any;
    name: string;
    code: string;
    description: string;
    location_id: any;
    capacity: number;
    requires_supervision: boolean;
    floor: string;
    zone: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockSchedule(overrides?: {}): {
    id: any;
    organization_id: any;
    name: string;
    start_date: string;
    end_date: string;
    status: string;
    published_at: null;
    notes: string;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockShift(overrides?: {}): {
    id: any;
    organization_id: any;
    schedule_id: any;
    shift_date: string;
    start_time: string;
    end_time: string;
    role_id: any;
    station_id: any;
    worker_id: any;
    status: string;
    break_minutes: number;
    actual_clock_in: null;
    actual_clock_out: null;
    notes: string;
    cancellation_reason: null;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockAvailability(overrides?: {}): {
    id: any;
    organization_id: any;
    worker_id: any;
    type: string;
    day_of_week: number;
    start_time: string;
    end_time: string;
    start_date: null;
    end_date: null;
    priority: string;
    reason: string;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockTimeOffRequest(overrides?: {}): {
    id: any;
    organization_id: any;
    worker_id: any;
    start_date: string;
    end_date: string;
    request_type: string;
    status: string;
    reason: string;
    notes: string;
    reviewed_at: null;
    reviewed_by: null;
    review_notes: null;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockSwapOffer(overrides?: {}): {
    id: any;
    organization_id: any;
    offered_shift_id: any;
    offering_worker_id: any;
    swap_type: string;
    target_worker_id: null;
    requested_shift_id: null;
    status: string;
    reason: string;
    notes: string;
    approved_at: null;
    approved_by: null;
    completed_at: null;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockSwapRequest(overrides?: {}): {
    id: any;
    organization_id: any;
    swap_offer_id: any;
    requesting_worker_id: any;
    offered_shift_id: null;
    status: string;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockWorkerRole(overrides?: {}): {
    id: any;
    organization_id: any;
    worker_id: any;
    role_id: any;
    proficiency_level: string;
    certification_date: string;
    notes: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockStationRequirement(overrides?: {}): {
    id: any;
    organization_id: any;
    station_id: any;
    role_id: any;
    min_workers: number;
    max_workers: number;
    priority: string;
    created_at: string;
    updated_at: string;
    created_by: any;
    updated_by: any;
};
export function createMockPool(): {
    query: any;
    connect: any;
};
export function createMockRequest(overrides?: {}): {
    user: any;
    params: {};
    query: {};
    body: {};
};
export function createMockResponse(): {
    status: any;
    json: any;
    send: any;
};
export function createMockNext(): any;
//# sourceMappingURL=testData.d.ts.map